### ISSUE TITLE
Contact attempt

### ISSUE THREAD

**Issue by renoirb** [RomainFleury/ngx-smile#1]
Bonjour,

Je suis aussi chez CGI et je tente de prendre contact avec des pairs qui font, eux aussi, du JavaScript moderne. Je suis tombé sur ça ici.

Est-tu au CCE? J'aimerai échanger quelques instants avec toi concernant notre travail, et voir comment s'entraîder chez notre employeur.

Pour ton projet de smiley, j'ai fait moi même plusieurs expériments du genre.

Pour me rejoindre, je te propose de m'écrire par le courriel du bureau, tu va me trouver facilement dans le address book Exchange.

Au plaisir!

**Comment by RomainFleury** [comment]
Bonjour, j'ai quitté CGI fin juin 2019.

**Comment by renoirb** [comment]
J'ai aussi quitté CGI. En Mars 2020.
